import re
import json

S1_HEADERS = [
    "NAME OF THE MEDICINAL PRODUCT",
    "NAME OF THE MEDICINAL PRODUCT(S)",
    "NAME OF THE MEDICINAL PRODUCTS",
    "1. NAME OF THE MEDICINAL PRODUCT",
    "1 NAME OF THE MEDICINAL PRODUCT"
    #"1", "1.0", "1."
]

S2_HEADERS = [
    "QUALITATIVE AND QUANTITATIVE COMPOSITION",
    "QUALITATIVE AND QUANTITATIVE COMPOSITIONS",
    "2. QUALITATIVE AND QUANTITATIVE COMPOSITION",
    "2 QUALITATIVE AND QUANTITATIVE COMPOSITION"
    #"2", "2.0", "2."
]

S3_HEADERS = [
    "PHARMACEUTICAL FORM",
    "3. PHARMACEUTICAL FORM",
    "3 PHARMACEUTICAL FORM"
    #"3", "3.0", "3."
]

S4_HEADERS = [
    "CLINICAL PARTICULARS", 
    "4. CLINICAL PARTICULARS",
    "4 CLINICAL PARTICULARS"
    #"4", "4.0", "4."
]
S4_1_HEADERS = [
    "THERAPEUTIC INDICATIONS",
    "4.1 THERAPEUTIC INDICATIONS"
    #"4.1", "4.1."

]
S4_2_HEADERS = [
    "POSOLOGY AND METHOD OF ADMINISTRATION",
    "4.2 POSOLOGY AND METHOD OF ADMINISTRATION"
    #"4.2", "4.2."
]
S4_3_HEADERS = [
    "CONTRAINDICATIONS",
    "4.3 CONTRAINDICATIONS"
    #"4.3", "4.3."
]
S4_4_HEADERS = [
    "SPECIAL WARNINGS AND PRECAUTIONS FOR USE",
    "4.4 SPECIAL WARNINGS AND PRECAUTIONS FOR USE"
    #"4.4", "4.4."
]   
S4_5_HEADERS = [
    "INTERACTION WITH OTHER MEDICINAL PRODUCTS AND OTHER FORMS OF INTERACTION", 
    "4.5 INTERACTION WITH OTHER MEDICINAL PRODUCTS AND OTHER FORMS OF INTERACTION"
    #"4.5", "4.5."
]
S4_6_HEADERS = [
    "FERTILITY, PREGNANCY AND LACTATION",
    "4.6 FERTILITY, PREGNANCY AND LACTATION"
    #"4.6", "4.6."
]
S4_7_HEADERS = [
    "EFFECTS ON ABILITY TO DRIVE AND USE MACHINES",
    "4.7 EFFECTS ON ABILITY TO DRIVE AND USE MACHINES"
    #"4.7", "4.7."
]
S4_8_HEADERS = [
    "UNDESIRABLE EFFECTS",
    "4.8 UNDESIRABLE EFFECTS"
    #"4.8", "4.8."
]
S4_9_HEADERS = [
    "OVERDOSE",
    "4.9 OVERDOSE"
    #"4.9", "4.9."

]

S5_HEADERS = [
    "PHARMACOLOGICAL PROPERTIES",
    "5. PHARMACOLOGICAL PROPERTIES", 
    "5 PHARMACOLOGICAL PROPERTIES"
    #"5", "5.0", "5."
]
S5_1_HEADERS = [
    "PHARMACODYNAMIC PROPERTIES",
    "5.1 PHARMACODYNAMIC PROPERTIES"
    #"5.1", "5.1."
]
S5_2_HEADERS = [
    "PHARMACOKINETIC PROPERTIES",
    "5.2 PHARMACOKINETIC PROPERTIES"

    #"5.2", "5.2."
]
S5_3_HEADERS = [
    "PRECLINICAL SAFETY DATA",
    "5.3 PRECLINICAL SAFETY DATA"
    #"5.3", "5.3."
]

S6_HEADERS = [
    "PHARMACEUTICAL PARTICULARS",
    "6. PHARMACEUTICAL PARTICULARS",
    "6 PHARMACEUTICAL PARTICULARS"
    #"6", "6.0", "6."
]
S6_1_HEADERS = [
    "LIST OF EXCIPIENTS",   
    "6.1 LIST OF EXCIPIENTS"
    #"6.1", "6.1."
]
S6_2_HEADERS = [
    "INCOMPATIBILITIES",
    "6.2 INCOMPATIBILITIES"
    #"6.2", "6.2."
]
S6_3_HEADERS = [
    "SHELF LIFE",
    "6.3 SHELF LIFE"
    #"6.3", "6.3."
]
S6_4_HEADERS = [
    "SPECIAL PRECAUTIONS FOR STORAGE",
    "6.4 SPECIAL PRECAUTIONS FOR STORAGE"
    #"6.4", "6.4."
]
S6_5_HEADERS = [
    "NATURE AND CONTENTS OF CONTAINER",
    "Nature AND CONTENTS OF CONTAINER(S)",
    "NATURE AND CONTENTS OF CONTAINERS",
    "6.5 NATURE AND CONTENTS OF CONTAINER"
    #"6.5", "6.5."
]
S6_6_HEADERS = [
    "SPECIAL PRECAUTIONS FOR DISPOSAL",
    "6.6 SPECIAL PRECAUTIONS FOR DISPOSAL"
    #"6.6", "6.6."
]
S7_HEADERS = [
    "MARKETING AUTHORISATION HOLDER",
    "MARKETING AUTHORISATION HOLDER(S)",
    "7 MARKETING AUTHORISATION HOLDER",
    "7. MARKETING AUTHORISATION HOLDER"
    #"7", "7.0", "7."
]
S8_HEADERS = [
    "MARKETING AUTHORISATION NUMBER",   
    "MARKETING AUTHORISATION NUMBERS",
    "Martketing Authorisation Number(s)",
    "8 MARKETING AUTHORISATION NUMBER(S)"  ,
    "8 MARKETING AUTHORISATION NUMBER"  ,
    "8. MARKETING AUTHORISATION NUMBER"
    #"8", "8.0", "8."
]
S9_HEADERS = [  
    "DATE OF FIRST AUTHORISATION",
    "DATE OF FIRST AUTHORISATION/RENEWAL OF THE AUTHORISATION",
    "9 DATE OF FIRST AUTHORISATION",
    "9. DATE OF FIRST AUTHORISATION",
    "9 DATE OF FIRST AUTHORISATION/RENEWAL OF THE AUTHORISATION",
    "RENEWAL OF THE AUTHORISATION",
    "9. DATE OF FIRST AUTHORISATION/RENEWAL OF THE AUTHORISATION"
]
S10_HEADERS = [
    "DATE OF REVISION OF THE TEXT",
    "10 DATE OF REVISION OF THE TEXT",
    
    "10. DATE OF REVISION OF THE TEXT"
]

ALL_KNOWN_HEADERS = set(h.strip().upper() for h in (S1_HEADERS + S2_HEADERS + S3_HEADERS + S4_HEADERS + S4_1_HEADERS + S4_2_HEADERS + S4_3_HEADERS + S4_4_HEADERS + S4_5_HEADERS + S4_6_HEADERS + S4_7_HEADERS + S4_8_HEADERS + S4_9_HEADERS + S5_HEADERS + S5_1_HEADERS + S5_2_HEADERS + S5_3_HEADERS + S6_HEADERS + S6_1_HEADERS + S6_2_HEADERS + S6_3_HEADERS + S6_4_HEADERS + S6_5_HEADERS + S6_6_HEADERS + S7_HEADERS + S8_HEADERS + S9_HEADERS +S10_HEADERS))

print ("Headers module loaded.")
print (f"Total known headers: {len(ALL_KNOWN_HEADERS)}")
