"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-only-change-me")
DEBUG = os.getenv("DJANGO_DEBUG", "0") == "1"

allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
ALLOWED_HOSTS = [h.strip() for h in allowed if h.strip()]

csrf = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if csrf.strip():
    CSRF_TRUSTED_ORIGINS = [x.strip() for x in csrf.split(",") if x.strip()]



# Application definition

INSTALLED_APPS = [
  
    "django.contrib.staticfiles",
    "orphan",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
]


ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = "config.wsgi.application"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {"context_processors": ["django.template.context_processors.request"]},
    }
]



STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"

# --- Django DB on Azure SQL using Entra token backend. This is not in use for now---
"""DATABASES = {
    "default": {
        "ENGINE": "config.db_backends.sqlserver_aad",
        "NAME": os.getenv("DB_IDMP_DATABASE"),
        "HOST": os.getenv("DB_SERVER"),
        "OPTIONS": {
            "driver": os.getenv("DRIVER", "ODBC Driver 18 for SQL Server"),
            "extra_params": "Connection Timeout=30;",
        },
    }
}"""



# We are NOT using Django DB for app logic (only reading via SQLAlchemy)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")